name: run all tasks

on:
  workflow_dispatch: # allows you to run this workflow manually from the Actions tab

jobs:
  example-doaj: # available as environment variable $GITHUB_JOB and context ${{ github.job }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install go-task 3.2.2
      run: |
        echo $GITHUB_PATH
        wget --no-verbose -O task.tar.gz https://github.com/go-task/task/releases/download/v3.2.2/task_linux_amd64.tar.gz
        tar -xzf task.tar.gz -C ~/.bin task && rm task.tar.gz
    - name: install OpenRefine and openrefine-client
      run: task install
    - name: run task ${{ github.job }}
      run: task "$GITHUB_JOB:main"
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ github.job }}
        path: ${{ github.job }}
    - name: commit and push if output changed # has nothing to do currently because of .gitignore
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git status
        git commit -m "latest change: $(date -u)" || exit 0
        git push
  example-duplicates: # available as environment variable $GITHUB_JOB and context ${{ github.job }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install go-task
      run: |
        wget https://github.com/go-task/task/releases/download/v3.2.2/task_linux_amd64.deb
        sudo apt-get install ./task_linux_amd64.deb && rm task_linux_amd64.deb
    - name: install OpenRefine and openrefine-client
      run: task install
    - name: run task ${{ github.job }}
      run: task "$GITHUB_JOB:main"
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ github.job }}
        path: ${{ github.job }}
    - name: commit and push if output changed # has nothing to do currently because of .gitignore
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git status
        git commit -m "latest change: $(date -u)" || exit 0
        git push
  example-powerhouse: # available as environment variable $GITHUB_JOB and context ${{ github.job }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install go-task
      run: |
        wget https://github.com/go-task/task/releases/download/v3.2.2/task_linux_amd64.deb
        sudo apt-get install ./task_linux_amd64.deb && rm task_linux_amd64.deb
    - name: install OpenRefine and openrefine-client
      run: task install
    - name: run task ${{ github.job }}
      run: task "$GITHUB_JOB:main"
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ github.job }}
        path: ${{ github.job }}
    - name: commit and push if output changed # has nothing to do currently because of .gitignore
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git status
        git commit -m "latest change: $(date -u)" || exit 0
        git push
